# Generated by Django 5.0.7 on 2024-07-22 18:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dg5lyidc8/image/upload/v1721074031/static/images/starwars.fbb5c1f1c2af.png', max_length=255, verbose_name='image'),
        ),
    ]
