# Generated by Django 5.0.7 on 2024-08-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0009_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='starwars'),
        ),
    ]
